import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { escapeHtml, parseMarkdown, renderMarkdown } from "../src/docs-parser.js";
import { parseOpenApi } from "../src/openapi-parser.js";

const root = fileURLToPath(new URL("..", import.meta.url));
const config = JSON.parse(await readFile(join(root, "docs.config.json"), "utf8"));
const contentDirectory = join(root, "content");
const generatedDirectory = join(root, "src", "generated");
const publicDirectory = join(root, "public", "docs");
const apiPublicDirectory = join(root, "public", "api");
const wellKnownDirectory = join(root, "public", ".well-known");

const fileNames = (await readdir(contentDirectory)).filter((fileName) => fileName.endsWith(".md")).sort();
const pages = [];
for (const fileName of fileNames) {
  const source = await readFile(join(contentDirectory, fileName), "utf8");
  pages.push({ ...parseMarkdown(source, basename(fileName)), source: `content/${fileName}` });
}
pages.sort((left, right) => left.order - right.order || left.slug.localeCompare(right.slug));

const openapiDirectory = join(root, "openapi");
const apiFileNames = (await readdir(openapiDirectory)).filter((fileName) => /\.(json|ya?ml)$/i.test(fileName)).sort();
const apiSpecs = [];
for (const fileName of apiFileNames) {
  const source = await readFile(join(openapiDirectory, fileName), "utf8");
  apiSpecs.push(parseOpenApi(source, fileName));
}
const apiIndex = {
  schemaVersion: 1,
  specs: apiSpecs.map((spec) => ({
    title: spec.title,
    version: spec.version,
    description: spec.description,
    openapi: spec.openapi,
    source: spec.source,
    operations: spec.operations.map((operation) => operation.id)
  })),
  operations: apiSpecs.flatMap((spec) => spec.operations)
};

const pageMap = new Map(pages.map((page) => [page.slug, page]));

function pageSummary(page) {
  return {
    slug: page.slug,
    path: `/docs/${page.slug}/`,
    title: page.title,
    description: page.description,
    section: page.section,
    tags: page.tags,
    audience: page.audience,
    related: page.related,
    version: page.version,
    locale: page.locale,
    updated: page.updated,
    stability: page.stability,
    source: page.source,
    headings: page.headings
  };
}

function buildNavigation() {
  const navigation = [];
  const used = new Set();
  for (const group of config.navigation || []) {
    const groupPages = (group.pages || []).map((slug) => pageMap.get(slug)).filter(Boolean);
    groupPages.forEach((page) => used.add(page.slug));
    if (groupPages.length) navigation.push({ group: String(group.group || "Docs"), pages: groupPages.map(pageSummary) });
  }

  const unlisted = pages.filter((page) => !used.has(page.slug));
  if (unlisted.length) navigation.push({ group: "Unlisted", pages: unlisted.map(pageSummary) });
  return navigation;
}

const navigation = buildNavigation();
const summaries = pages.map(pageSummary);
const agentManifest = {
  schemaVersion: "vessel.agent-manifest/v1",
  name: config.agent.name,
  description: config.agent.description,
  sourceOfTruth: "git",
  site: config.site,
  versions: config.versions || [],
  locales: config.locales || [],
  navigation,
  api: {
    specs: apiIndex.specs,
    operations: apiIndex.operations.map((operation) => ({
      id: operation.id,
      method: operation.method,
      path: operation.path,
      summary: operation.summary,
      tags: operation.tags,
      source: operation.source
    }))
  },
  surfaces: {
    humanDocs: "/docs/",
    docsIndex: "/api/docs/index",
    docsSearch: "/api/docs/search?q={query}",
    docsAudit: "/api/docs/audit",
    apiIndex: "/api/openapi/index",
    apiOperation: "/api/openapi/operation?id={operationId}",
    apiPlayground: "/api/",
    mcp: "/api/mcp",
    llms: "/llms.txt",
    fullContext: "/llms-full.txt",
    skill: "/skill.md",
    permissions: "/agent-permissions.json"
  },
  capabilities: config.agent.capabilities.map((name) => ({ name, access: "read", transports: ["http", "mcp"] })),
  constraints: config.agent.constraints,
  pages: summaries
};
const agentPermissions = {
  schemaVersion: "vessel.agent-permissions/v1",
  default: "deny",
  read: ["docs.index", "docs.search", "docs.page", "docs.examples", "docs.audit", "api.index", "api.operation", "mcp.resources", "mcp.tools"],
  write: [],
  requiresHumanApproval: ["repository.write", "content.publish", "provider.request"],
  notes: "This contract is read-only. Repository or publishing changes require a separate human-reviewed workflow."
};

await mkdir(generatedDirectory, { recursive: true });
await mkdir(publicDirectory, { recursive: true });
await mkdir(apiPublicDirectory, { recursive: true });
await mkdir(wellKnownDirectory, { recursive: true });

await writeFile(
  join(generatedDirectory, "docs-index.js"),
  `// Generated by scripts/build-docs.mjs. Edit docs.config.json and content/*.md instead.\nexport const docsIndex = ${JSON.stringify(pages, null, 2)};\nexport const siteConfig = ${JSON.stringify(config, null, 2)};\nexport const docsNavigation = ${JSON.stringify(navigation, null, 2)};\nexport const agentManifest = ${JSON.stringify(agentManifest, null, 2)};\nexport const agentPermissions = ${JSON.stringify(agentPermissions, null, 2)};\n`
);
await writeFile(
  join(generatedDirectory, "openapi-index.js"),
  `// Generated by scripts/build-docs.mjs. Edit openapi/*.json instead.\nexport const apiIndex = ${JSON.stringify(apiIndex, null, 2)};\n`
);
await writeFile(
  join(publicDirectory, "index.json"),
  `${JSON.stringify({ schemaVersion: 1, site: config.site, versions: config.versions || [], locales: config.locales || [], navigation, pages: summaries }, null, 2)}\n`
);
await writeFile(join(root, "public", "agent-manifest.json"), `${JSON.stringify(agentManifest, null, 2)}\n`);
await writeFile(join(wellKnownDirectory, "agent-manifest.json"), `${JSON.stringify(agentManifest, null, 2)}\n`);
await writeFile(join(root, "public", "agent-permissions.json"), `${JSON.stringify(agentPermissions, null, 2)}\n`);
const sitemapUrls = ["/", "/docs/", "/api/", ...pages.map((page) => `/docs/${page.slug}/`), ...apiIndex.operations.map((operation) => `/api/${operation.id}/`)];
await writeFile(
  join(root, "public", "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapUrls.map((url) => `  <url><loc>${escapeHtml(url)}</loc></url>`).join("\n")}\n</urlset>\n`
);

const skillGroups = navigation
  .map((group) => `### ${group.group}\n${group.pages.map((page) => `- [${page.title}](${page.path}) — ${page.description}`).join("\n")}`)
  .join("\n\n");
await writeFile(
  join(root, "public", "skill.md"),
  `# Vessel documentation skill\n\nUse this skill when answering questions about Vessel or implementing against its documentation. The source of truth is the Git-backed Markdown index, not model memory.\n\n## Read-only workflow\n\n1. Fetch [/api/docs/index](/api/docs/index) to discover the current navigation, version, locale, and page metadata.\n2. Search [/api/docs/search?q={query}](/api/docs/search?q=checkout) for the smallest relevant context.\n3. Fetch [/api/docs/page?slug={slug}](/api/docs/page?slug=quickstart) for the complete source page.\n4. Cite the returned docs path (/docs/<slug>/) when a page supports the answer.\n5. Run [/api/docs/audit](/api/docs/audit) before proposing documentation changes.\n\n## Rules\n\n- Treat this surface as read-only.\n- Do not invent endpoints, parameters, permissions, or behavior absent from a source page.\n- Prefer pages marked stability: stable and the configured current version.\n- Ask for human approval before repository writes, publishing, or provider requests.\n- If the source does not answer the question, say what is missing.\n\n## Available pages\n\n${skillGroups}\n\n## Machine surfaces\n\n- MCP: [/api/mcp](/api/mcp)\n- API reference and request preview: [/api/](/api/)\n- API operation index: [/api/openapi/index](/api/openapi/index)\n- Manifest: [/agent-manifest.json](/agent-manifest.json)\n- Permissions: [/agent-permissions.json](/agent-permissions.json)\n- Full context: [/llms-full.txt](/llms-full.txt)\n`
);

function renderNavigation(currentSlug) {
  return navigation.map((group) => `<div class="docs-nav-group"><span>${escapeHtml(group.group)}</span>${group.pages.map((page) => `<a class="${page.slug === currentSlug ? "active" : ""}" href="${page.path}">${escapeHtml(page.title)}</a>`).join("")}</div>`).join("");
}

function renderPage(page, index) {
  const previous = pages[index - 1];
  const next = pages[index + 1];
  const navigationLinks = [
    previous ? `<a href="/docs/${previous.slug}/"><span>Previous</span><strong>${escapeHtml(previous.title)}</strong></a>` : "",
    next ? `<a class="next" href="/docs/${next.slug}/"><span>Next</span><strong>${escapeHtml(next.title)}</strong></a>` : ""
  ].join("");
  const metadata = [page.version, page.locale, page.updated ? `Updated ${page.updated}` : ""].filter(Boolean).map((item) => `<span>${escapeHtml(item)}</span>`).join("");
  return `<!doctype html>
<html lang="${escapeHtml(page.locale)}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(page.title)} · ${escapeHtml(config.site.name)}</title>
    <meta name="description" content="${escapeHtml(page.description)}" />
    <link rel="stylesheet" href="/docs/docs.css" />
  </head>
  <body data-version="${escapeHtml(page.version)}" data-locale="${escapeHtml(page.locale)}">
    <main class="docs-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> ${escapeHtml(config.site.name)}</a><a class="docs-source" href="${escapeHtml(config.repository.url)}" target="_blank" rel="noreferrer">View source ↗</a></header>
      <div class="docs-layout">
        <aside class="docs-aside"><span class="docs-kicker">${escapeHtml(page.section)}</span><h1>${escapeHtml(page.title)}</h1><p>${escapeHtml(page.description)}</p><div class="docs-meta">${metadata}</div><div class="docs-tags">${page.tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join("")}</div><a class="docs-index-link" href="/docs/">Browse the source index <span>→</span></a><nav class="docs-nav" aria-label="Documentation navigation">${renderNavigation(page.slug)}</nav></aside>
        <article class="docs-article">${renderMarkdown(page.content)}<nav class="docs-pagination">${navigationLinks}</nav></article>
      </div>
      <footer class="docs-footer"><span>Generated from ${escapeHtml(page.source)}</span><div class="docs-footer-links"><a href="${escapeHtml(`${config.repository.url}/edit/${config.repository.branch}/${page.source}`)}" target="_blank" rel="noreferrer">Edit on GitHub ↗</a><a href="/api/docs/page?slug=${encodeURIComponent(page.slug)}">JSON page ↗</a></div></footer>
    </main>
    <script src="/docs/docs.js"></script>
  </body>
</html>
`;
}

function renderIndex() {
  const groups = navigation.map((group) => `
    <section class="docs-index-section">
      <div class="docs-index-section-heading"><span class="docs-kicker">${escapeHtml(group.group)}</span><span>${group.pages.length} ${group.pages.length === 1 ? "page" : "pages"}</span></div>
      <div class="docs-index-grid">${group.pages.map((page) => `
        <a class="docs-card" href="${page.path}" data-doc-card data-doc-search="${escapeHtml(`${page.title} ${page.description} ${page.tags.join(" ")} ${page.slug}`)}">
          <span class="docs-card-meta">${escapeHtml(page.version)} · ${escapeHtml(page.locale)} · ${escapeHtml(page.slug)}</span>
          <strong>${escapeHtml(page.title)}</strong>
          <p>${escapeHtml(page.description)}</p>
          <span class="docs-card-arrow">Read page <span>→</span></span>
        </a>`).join("")}</div>
    </section>`).join("").trimStart();

  return `<!doctype html>
<html lang="${escapeHtml(config.site.defaultLocale || "en")}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(config.site.name)} documentation</title>
    <meta name="description" content="${escapeHtml(config.site.description)}" />
    <link rel="stylesheet" href="/docs/docs.css" />
  </head>
  <body>
    <main class="docs-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> ${escapeHtml(config.site.name)}</a><a class="docs-source" href="${escapeHtml(config.repository.url)}" target="_blank" rel="noreferrer">View source ↗</a></header>
      <section class="docs-index-hero">
        <span class="docs-kicker">Source index · ${pages.length} pages · ${escapeHtml(config.site.defaultVersion || "current")}</span>
        <h1>Documentation for humans and agents.</h1>
        <p>Every page starts as readable Markdown in <code>content/</code>, then becomes a versioned, navigable web page, a searchable JSON index, and a read-only MCP resource.</p>
        <div class="docs-index-actions"><a href="/api/docs/index">JSON index ↗</a><a href="/api/">API reference ↗</a><a href="/agent-manifest.json">Agent manifest ↗</a><a href="/api/mcp">MCP manifest ↗</a></div>
        <div class="docs-search-box"><label for="docs-search">Search this source <kbd>/</kbd></label><input id="docs-search" type="search" placeholder="Search pages, tags, and descriptions" autocomplete="off" aria-controls="docs-results" /><span data-doc-count aria-live="polite">${pages.length} pages</span></div>
      </section>
      <p class="docs-search-empty" data-doc-empty hidden>No pages match that search.</p>
      <div id="docs-results">${groups}</div>
      <footer class="docs-footer"><span>Generated from docs.config.json and content/*.md</span><a href="/skill.md">Agent skill ↗</a></footer>
    </main>
    <script src="/docs/docs.js"></script>
  </body>
</html>
`;
}

function renderApiIndex() {
  const operations = apiIndex.operations.map((operation) => `
    <a class="api-operation-card" href="/api/${operation.id}/" data-operation-id="${escapeHtml(operation.id)}">
      <span class="api-operation-card__method api-method--${operation.method.toLowerCase()}">${escapeHtml(operation.method)}</span>
      <span class="api-operation-card__path">${escapeHtml(operation.path)}</span>
      <strong>${escapeHtml(operation.summary)}</strong>
      <p>${escapeHtml(operation.description || "Generated from the OpenAPI contract.")}</p>
      <span class="api-operation-card__arrow">Open reference <span>→</span></span>
    </a>`).join("");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>API reference · ${escapeHtml(apiSpecs[0]?.title || config.site.name)}</title>
    <meta name="description" content="${escapeHtml(apiSpecs[0]?.description || "Generated API reference and request-preview playground.")}" />
    <link rel="stylesheet" href="/docs/docs.css" />
    <link rel="stylesheet" href="/api/api.css" />
  </head>
  <body>
    <main class="docs-shell api-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> ${escapeHtml(config.site.name)}</a><a class="docs-source" href="/docs/">Human docs ↗</a></header>
      <section class="api-hero">
        <span class="docs-kicker">API reference · OpenAPI ${escapeHtml(apiSpecs[0]?.openapi || "3")}</span>
        <h1>Make the API impossible to misunderstand.</h1>
        <p>${escapeHtml(apiSpecs[0]?.description || "Generated from the repository's OpenAPI contract.")}</p>
        <div class="docs-index-actions"><a href="#playground">Try the request preview ↓</a><a href="/api/index.json">JSON contract ↗</a></div>
      </section>
      <section class="api-playground" id="playground" data-api-explorer data-index-url="/api/index.json">
        <noscript>Enable JavaScript to use the request-preview playground. The complete operation references remain available below.</noscript>
      </section>
      <section class="api-operations" aria-label="API operations">
        <div class="api-section-heading"><span class="docs-kicker">Operations</span><span>${apiIndex.operations.length} generated endpoints · ${escapeHtml(apiIndex.specs[0]?.version || "current")}</span></div>
        <div class="api-operation-grid">${operations}</div>
      </section>
      <footer class="docs-footer"><span>Generated from ${escapeHtml(apiSpecs[0]?.source || "openapi/*.json")}</span><a href="/api/mcp">MCP API tools ↗</a></footer>
    </main>
    <script type="module" src="/api/api-explorer.js"></script>
  </body>
</html>
`;
}

function renderApiOperation(operation) {
  const requestExample = operation.requestBody?.example;
  const response = operation.responses.find((item) => /^2/.test(item.status)) || operation.responses[0];
  const responseExample = response?.example;
  const schemas = [
    operation.requestBody?.schema ? { label: "Request schema", schema: operation.requestBody.schema } : null,
    response?.schema ? { label: `Response schema · ${response.status}`, schema: response.schema } : null
  ].filter(Boolean);
  const authLabel = operation.security?.length ? "Authentication required" : "Public operation";
  const tags = operation.tags.length ? operation.tags.join(" · ") : "Untagged";
  const responseList = operation.responses.length
    ? `<section><h2>Responses</h2><div class="api-response-list">${operation.responses.map((item) => `<div class="api-response"><code class="api-response__status api-response__status--${item.status.startsWith("2") ? "success" : "error"}">${escapeHtml(item.status)}</code><span>${escapeHtml(item.description || "No description provided.")}</span><small>${escapeHtml(item.contentType || "No response body")}</small></div>`).join("")}</div></section>`
    : "";
  const parameters = operation.parameters.length
    ? `<section><h2>Parameters</h2><div class="api-parameter-list">${operation.parameters.map((parameter) => `<div class="api-parameter"><code>${escapeHtml(parameter.name)}</code><span>${escapeHtml(parameter.in)}${parameter.required ? " · required" : ""}</span><p>${escapeHtml(parameter.description || "No description provided.")}</p></div>`).join("")}</div></section>`
    : "";
  const sections = [
    parameters,
    requestExample !== undefined ? `<section><h2>Request example</h2><pre><code>${escapeHtml(JSON.stringify(requestExample, null, 2))}</code></pre></section>` : "",
    responseExample !== undefined ? `<section><h2>Success response · ${escapeHtml(response.status)}</h2><pre><code>${escapeHtml(JSON.stringify(responseExample, null, 2))}</code></pre></section>` : "",
    schemas.length ? `<section><h2>Schemas</h2><div class="api-schema-grid">${schemas.map((item) => `<div class="api-schema"><span>${escapeHtml(item.label)}</span><pre><code>${escapeHtml(JSON.stringify(item.schema, null, 2))}</code></pre></div>`).join("")}</div></section>` : "",
    responseList
  ].filter(Boolean).join("\n");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(operation.summary)} · API reference</title>
    <meta name="description" content="${escapeHtml(operation.description || operation.summary)}" />
    <link rel="stylesheet" href="/docs/docs.css" />
    <link rel="stylesheet" href="/api/api.css" />
  </head>
  <body>
    <main class="docs-shell api-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> ${escapeHtml(config.site.name)}</a><a class="docs-source" href="/api/">API reference ↗</a></header>
      <article class="api-operation-page">
        <div class="api-operation-heading"><span class="api-operation-card__method api-method--${operation.method.toLowerCase()}">${escapeHtml(operation.method)}</span><code>${escapeHtml(operation.path)}</code></div>
        <h1>${escapeHtml(operation.summary)}</h1>
        <p class="api-operation-lede">${escapeHtml(operation.description || "Generated from the OpenAPI contract.")}</p>
        <div class="api-operation-meta"><span>${escapeHtml(authLabel)}</span><span>${escapeHtml(tags)}</span><span>${escapeHtml(operation.source)}</span></div>
        <div class="docs-index-actions"><a href="/api/#${encodeURIComponent(operation.id)}">Open request preview ↗</a><a href="/api/openapi/operation?id=${encodeURIComponent(operation.id)}">JSON operation ↗</a></div>${sections ? `\n        ${sections}` : ""}
      </article>
    </main>
  </body>
</html>
`;
}

await writeFile(join(publicDirectory, "index.html"), renderIndex());
await writeFile(join(apiPublicDirectory, "index.json"), `${JSON.stringify(apiIndex, null, 2)}\n`);
await writeFile(join(apiPublicDirectory, "index.html"), renderApiIndex());
for (const operation of apiIndex.operations) {
  const operationDirectory = join(apiPublicDirectory, operation.id);
  await mkdir(operationDirectory, { recursive: true });
  await writeFile(join(operationDirectory, "index.json"), `${JSON.stringify(operation, null, 2)}\n`);
  await writeFile(join(operationDirectory, "index.html"), renderApiOperation(operation));
}

for (const page of pages) {
  await writeFile(join(publicDirectory, `${page.slug}.json`), `${JSON.stringify(page, null, 2)}\n`);
  const pageDirectory = join(publicDirectory, page.slug);
  await mkdir(pageDirectory, { recursive: true });
  await writeFile(join(pageDirectory, "index.html"), renderPage(page, pages.indexOf(page)));
}

console.log(`Indexed ${pages.length} documentation pages across ${navigation.length} navigation groups.`);
