import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { escapeHtml, parseMarkdown, renderMarkdown } from "../src/docs-parser.js";

const root = fileURLToPath(new URL("..", import.meta.url));
const config = JSON.parse(await readFile(join(root, "docs.config.json"), "utf8"));
const contentDirectory = join(root, "content");
const generatedDirectory = join(root, "src", "generated");
const publicDirectory = join(root, "public", "docs");
const wellKnownDirectory = join(root, "public", ".well-known");

const fileNames = (await readdir(contentDirectory)).filter((fileName) => fileName.endsWith(".md")).sort();
const pages = [];
for (const fileName of fileNames) {
  const source = await readFile(join(contentDirectory, fileName), "utf8");
  pages.push({ ...parseMarkdown(source, basename(fileName)), source: `content/${fileName}` });
}
pages.sort((left, right) => left.order - right.order || left.slug.localeCompare(right.slug));

const pageMap = new Map(pages.map((page) => [page.slug, page]));

function pageSummary(page) {
  return {
    slug: page.slug,
    path: `/docs/${page.slug}/`,
    title: page.title,
    description: page.description,
    section: page.section,
    tags: page.tags,
    audience: page.audience,
    related: page.related,
    version: page.version,
    locale: page.locale,
    updated: page.updated,
    stability: page.stability,
    source: page.source,
    headings: page.headings
  };
}

function buildNavigation() {
  const navigation = [];
  const used = new Set();
  for (const group of config.navigation || []) {
    const groupPages = (group.pages || []).map((slug) => pageMap.get(slug)).filter(Boolean);
    groupPages.forEach((page) => used.add(page.slug));
    if (groupPages.length) navigation.push({ group: String(group.group || "Docs"), pages: groupPages.map(pageSummary) });
  }

  const unlisted = pages.filter((page) => !used.has(page.slug));
  if (unlisted.length) navigation.push({ group: "Unlisted", pages: unlisted.map(pageSummary) });
  return navigation;
}

const navigation = buildNavigation();
const summaries = pages.map(pageSummary);
const agentManifest = {
  schemaVersion: "vessel.agent-manifest/v1",
  name: config.agent.name,
  description: config.agent.description,
  sourceOfTruth: "git",
  site: config.site,
  versions: config.versions || [],
  locales: config.locales || [],
  navigation,
  surfaces: {
    humanDocs: "/docs/",
    docsIndex: "/api/docs/index",
    docsSearch: "/api/docs/search?q={query}",
    docsAudit: "/api/docs/audit",
    mcp: "/api/mcp",
    llms: "/llms.txt",
    fullContext: "/llms-full.txt",
    skill: "/skill.md",
    permissions: "/agent-permissions.json"
  },
  capabilities: config.agent.capabilities.map((name) => ({ name, access: "read", transports: ["http", "mcp"] })),
  constraints: config.agent.constraints,
  pages: summaries
};
const agentPermissions = {
  schemaVersion: "vessel.agent-permissions/v1",
  default: "deny",
  read: ["docs.index", "docs.search", "docs.page", "docs.examples", "docs.audit", "mcp.resources", "mcp.tools"],
  write: [],
  requiresHumanApproval: ["repository.write", "content.publish", "provider.request"],
  notes: "This contract is read-only. Repository or publishing changes require a separate human-reviewed workflow."
};

await mkdir(generatedDirectory, { recursive: true });
await mkdir(publicDirectory, { recursive: true });
await mkdir(wellKnownDirectory, { recursive: true });

await writeFile(
  join(generatedDirectory, "docs-index.js"),
  `// Generated by scripts/build-docs.mjs. Edit docs.config.json and content/*.md instead.\nexport const docsIndex = ${JSON.stringify(pages, null, 2)};\nexport const siteConfig = ${JSON.stringify(config, null, 2)};\nexport const docsNavigation = ${JSON.stringify(navigation, null, 2)};\nexport const agentManifest = ${JSON.stringify(agentManifest, null, 2)};\nexport const agentPermissions = ${JSON.stringify(agentPermissions, null, 2)};\n`
);
await writeFile(
  join(publicDirectory, "index.json"),
  `${JSON.stringify({ schemaVersion: 1, site: config.site, versions: config.versions || [], locales: config.locales || [], navigation, pages: summaries }, null, 2)}\n`
);
await writeFile(join(root, "public", "agent-manifest.json"), `${JSON.stringify(agentManifest, null, 2)}\n`);
await writeFile(join(wellKnownDirectory, "agent-manifest.json"), `${JSON.stringify(agentManifest, null, 2)}\n`);
await writeFile(join(root, "public", "agent-permissions.json"), `${JSON.stringify(agentPermissions, null, 2)}\n`);
const sitemapUrls = ["/", "/docs/", ...pages.map((page) => `/docs/${page.slug}/`)];
await writeFile(
  join(root, "public", "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapUrls.map((url) => `  <url><loc>${escapeHtml(url)}</loc></url>`).join("\n")}\n</urlset>\n`
);

const skillGroups = navigation
  .map((group) => `### ${group.group}\n${group.pages.map((page) => `- [${page.title}](${page.path}) — ${page.description}`).join("\n")}`)
  .join("\n\n");
await writeFile(
  join(root, "public", "skill.md"),
  `# Vessel documentation skill\n\nUse this skill when answering questions about Vessel or implementing against its documentation. The source of truth is the Git-backed Markdown index, not model memory.\n\n## Read-only workflow\n\n1. Fetch [/api/docs/index](/api/docs/index) to discover the current navigation, version, locale, and page metadata.\n2. Search [/api/docs/search?q={query}](/api/docs/search?q=checkout) for the smallest relevant context.\n3. Fetch [/api/docs/page?slug={slug}](/api/docs/page?slug=quickstart) for the complete source page.\n4. Cite the returned docs path (/docs/<slug>/) when a page supports the answer.\n5. Run [/api/docs/audit](/api/docs/audit) before proposing documentation changes.\n\n## Rules\n\n- Treat this surface as read-only.\n- Do not invent endpoints, parameters, permissions, or behavior absent from a source page.\n- Prefer pages marked stability: stable and the configured current version.\n- Ask for human approval before repository writes, publishing, or provider requests.\n- If the source does not answer the question, say what is missing.\n\n## Available pages\n\n${skillGroups}\n\n## Machine surfaces\n\n- MCP: [/api/mcp](/api/mcp)\n- Manifest: [/agent-manifest.json](/agent-manifest.json)\n- Permissions: [/agent-permissions.json](/agent-permissions.json)\n- Full context: [/llms-full.txt](/llms-full.txt)\n`
);

function renderNavigation(currentSlug) {
  return navigation.map((group) => `<div class="docs-nav-group"><span>${escapeHtml(group.group)}</span>${group.pages.map((page) => `<a class="${page.slug === currentSlug ? "active" : ""}" href="${page.path}">${escapeHtml(page.title)}</a>`).join("")}</div>`).join("");
}

function renderPage(page, index) {
  const previous = pages[index - 1];
  const next = pages[index + 1];
  const navigationLinks = [
    previous ? `<a href="/docs/${previous.slug}/"><span>Previous</span><strong>${escapeHtml(previous.title)}</strong></a>` : "",
    next ? `<a class="next" href="/docs/${next.slug}/"><span>Next</span><strong>${escapeHtml(next.title)}</strong></a>` : ""
  ].join("");
  const metadata = [page.version, page.locale, page.updated ? `Updated ${page.updated}` : ""].filter(Boolean).map((item) => `<span>${escapeHtml(item)}</span>`).join("");
  return `<!doctype html>
<html lang="${escapeHtml(page.locale)}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(page.title)} · ${escapeHtml(config.site.name)}</title>
    <meta name="description" content="${escapeHtml(page.description)}" />
    <link rel="stylesheet" href="/docs/docs.css" />
  </head>
  <body data-version="${escapeHtml(page.version)}" data-locale="${escapeHtml(page.locale)}">
    <main class="docs-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> ${escapeHtml(config.site.name)}</a><a class="docs-source" href="https://github.com/everyai-com/mintly-alternative" target="_blank" rel="noreferrer">View source ↗</a></header>
      <div class="docs-layout">
        <aside class="docs-aside"><span class="docs-kicker">${escapeHtml(page.section)}</span><h1>${escapeHtml(page.title)}</h1><p>${escapeHtml(page.description)}</p><div class="docs-meta">${metadata}</div><div class="docs-tags">${page.tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join("")}</div><a class="docs-index-link" href="/docs/">Browse the source index <span>→</span></a><nav class="docs-nav" aria-label="Documentation navigation">${renderNavigation(page.slug)}</nav></aside>
        <article class="docs-article">${renderMarkdown(page.content)}<nav class="docs-pagination">${navigationLinks}</nav></article>
      </div>
      <footer class="docs-footer"><span>Generated from ${escapeHtml(page.source)}</span><a href="/api/docs/page?slug=${encodeURIComponent(page.slug)}">JSON page ↗</a></footer>
    </main>
  </body>
</html>
`;
}

function renderIndex() {
  const groups = navigation.map((group) => `
    <section class="docs-index-section">
      <div class="docs-index-section-heading"><span class="docs-kicker">${escapeHtml(group.group)}</span><span>${group.pages.length} ${group.pages.length === 1 ? "page" : "pages"}</span></div>
      <div class="docs-index-grid">${group.pages.map((page) => `
        <a class="docs-card" href="${page.path}">
          <span class="docs-card-meta">${escapeHtml(page.version)} · ${escapeHtml(page.locale)} · ${escapeHtml(page.slug)}</span>
          <strong>${escapeHtml(page.title)}</strong>
          <p>${escapeHtml(page.description)}</p>
          <span class="docs-card-arrow">Read page <span>→</span></span>
        </a>`).join("")}</div>
    </section>`).join("").trimStart();

  return `<!doctype html>
<html lang="${escapeHtml(config.site.defaultLocale || "en")}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(config.site.name)} documentation</title>
    <meta name="description" content="${escapeHtml(config.site.description)}" />
    <link rel="stylesheet" href="/docs/docs.css" />
  </head>
  <body>
    <main class="docs-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> ${escapeHtml(config.site.name)}</a><a class="docs-source" href="https://github.com/everyai-com/mintly-alternative" target="_blank" rel="noreferrer">View source ↗</a></header>
      <section class="docs-index-hero">
        <span class="docs-kicker">Source index · ${pages.length} pages · ${escapeHtml(config.site.defaultVersion || "current")}</span>
        <h1>Documentation for humans and agents.</h1>
        <p>Every page starts as readable Markdown in <code>content/</code>, then becomes a versioned, navigable web page, a searchable JSON index, and a read-only MCP resource.</p>
        <div class="docs-index-actions"><a href="/api/docs/index">JSON index ↗</a><a href="/agent-manifest.json">Agent manifest ↗</a><a href="/api/mcp">MCP manifest ↗</a></div>
      </section>
      ${groups}
      <footer class="docs-footer"><span>Generated from docs.config.json and content/*.md</span><a href="/skill.md">Agent skill ↗</a></footer>
    </main>
  </body>
</html>
`;
}

await writeFile(join(publicDirectory, "index.html"), renderIndex());

for (const page of pages) {
  await writeFile(join(publicDirectory, `${page.slug}.json`), `${JSON.stringify(page, null, 2)}\n`);
  const pageDirectory = join(publicDirectory, page.slug);
  await mkdir(pageDirectory, { recursive: true });
  await writeFile(join(pageDirectory, "index.html"), renderPage(page, pages.indexOf(page)));
}

console.log(`Indexed ${pages.length} documentation pages across ${navigation.length} navigation groups.`);
