import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { escapeHtml, parseMarkdown, renderMarkdown } from "../src/docs-parser.js";

const root = fileURLToPath(new URL("..", import.meta.url));
const contentDirectory = join(root, "content");
const generatedDirectory = join(root, "src", "generated");
const publicDirectory = join(root, "public", "docs");

const fileNames = (await readdir(contentDirectory)).filter((fileName) => fileName.endsWith(".md")).sort();
const pages = [];
for (const fileName of fileNames) {
  const source = await readFile(join(contentDirectory, fileName), "utf8");
  pages.push(parseMarkdown(source, basename(fileName)));
}
pages.sort((left, right) => left.order - right.order || left.slug.localeCompare(right.slug));

await mkdir(generatedDirectory, { recursive: true });
await mkdir(publicDirectory, { recursive: true });
await writeFile(join(generatedDirectory, "docs-index.js"), `// Generated by scripts/build-docs.mjs. Edit content/*.md instead.\nexport const docsIndex = ${JSON.stringify(pages, null, 2)};\n`);
await writeFile(join(publicDirectory, "index.json"), `${JSON.stringify({ version: 1, pages }, null, 2)}\n`);

function renderPage(page, index) {
  const previous = pages[index - 1];
  const next = pages[index + 1];
  const navigation = [
    previous ? `<a href="/docs/${previous.slug}/"><span>Previous</span><strong>${escapeHtml(previous.title)}</strong></a>` : "",
    next ? `<a class="next" href="/docs/${next.slug}/"><span>Next</span><strong>${escapeHtml(next.title)}</strong></a>` : ""
  ].join("");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(page.title)} · Vessel</title>
    <meta name="description" content="${escapeHtml(page.description)}" />
    <link rel="stylesheet" href="/docs/docs.css" />
  </head>
  <body>
    <main class="docs-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> Vessel</a><a class="docs-source" href="https://github.com/everyai-com/mintly-alternative" target="_blank" rel="noreferrer">View source ↗</a></header>
      <div class="docs-layout">
        <aside class="docs-aside"><span class="docs-kicker">${escapeHtml(page.section)}</span><h1>${escapeHtml(page.title)}</h1><p>${escapeHtml(page.description)}</p><div class="docs-tags">${page.tags.map((tag) => `<span>${escapeHtml(tag)}</span>`).join("")}</div><a class="docs-index-link" href="/docs/">Browse the source index <span>→</span></a></aside>
        <article class="docs-article">${renderMarkdown(page.content)}<nav class="docs-pagination">${navigation}</nav></article>
      </div>
      <footer class="docs-footer"><span>Generated from content/${page.slug}.md</span><a href="/api/docs/page?slug=${encodeURIComponent(page.slug)}">JSON page ↗</a></footer>
    </main>
  </body>
</html>
`;
}

function renderIndex() {
  const cards = pages.map((page) => `
    <a class="docs-card" href="/docs/${page.slug}/">
      <span class="docs-card-meta">${escapeHtml(page.section)} · ${escapeHtml(page.slug)}</span>
      <strong>${escapeHtml(page.title)}</strong>
      <p>${escapeHtml(page.description)}</p>
      <span class="docs-card-arrow">Read page <span>→</span></span>
    </a>`).join("");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Vessel documentation</title>
    <meta name="description" content="Source documentation for humans, developers, and AI agents." />
    <link rel="stylesheet" href="/docs/docs.css" />
  </head>
  <body>
    <main class="docs-shell">
      <header class="docs-header"><a class="docs-brand" href="/"><span>V</span> Vessel</a><a class="docs-source" href="https://github.com/everyai-com/mintly-alternative" target="_blank" rel="noreferrer">View source ↗</a></header>
      <section class="docs-index-hero">
        <span class="docs-kicker">Source index · ${pages.length} pages</span>
        <h1>Documentation for humans and agents.</h1>
        <p>Every page starts as readable Markdown in <code>content/</code>, then becomes a fast web page, a searchable JSON index, and a read-only MCP resource.</p>
        <div class="docs-index-actions"><a href="/api/docs/index">JSON index ↗</a><a href="/api/mcp">MCP manifest ↗</a></div>
      </section>
      <section class="docs-index-grid" aria-label="Documentation pages">${cards}</section>
      <footer class="docs-footer"><span>Generated from content/*.md</span><a href="/api/docs/index">JSON index ↗</a></footer>
    </main>
  </body>
</html>
`;
}

await writeFile(join(publicDirectory, "index.html"), renderIndex());

for (const page of pages) {
  await writeFile(join(publicDirectory, `${page.slug}.json`), `${JSON.stringify(page, null, 2)}\n`);
  const pageDirectory = join(publicDirectory, page.slug);
  await mkdir(pageDirectory, { recursive: true });
  await writeFile(join(pageDirectory, "index.html"), renderPage(page, pages.indexOf(page)));
}

console.log(`Indexed ${pages.length} documentation pages.`);
